name: Documentation

on:
  push:
    branches:
      - main
      - "*-snapshot"
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Documentation
        run: |
          ./gradlew dokkaGenerate -Prelease
          mkdir -p ./docs/handbook/dokka
          mv ./components/buttons/build/dokka/html/* ./docs/handbook/dokka
          
          ./gradlew :docs:sample:jsBrowserDistribution
          mkdir -p ./docs/handbook/compose
          mv ./docs/sample/build/dist/js/productionExecutable/* ./docs/handbook/compose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-files
          path: ./docs/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build-files
          path: ./docs
      - name: Build & Deploy to correct path
        run: |
          cd docs
          pip install zensical
          
          # 判断是否为 snapshot 分支
          if [[ "${GITHUB_REF_NAME}" == *-snapshot ]]; then
            echo "Running Snapshot build -> /snapshot"
            zensical build --clean --base-path /snapshot
            mkdir -p ./site/snapshot
            mv ./site/* ./site/snapshot/ 2>/dev/null || true
          else
            echo "Running Production build"
            zensical build --clean
          fi
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/site
      - uses: actions/deploy-pages@v4
        id: deployment
