name: Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Documentation
        run: |
          ./gradlew dokkaGenerate -Prelease
          mkdir -p ./docs/handbook/dokka
          mv ./components/buttons/build/dokka/html/* ./docs/handbook/dokka
          
          ./gradlew :docs:sample:jsBrowserDistribution
          mkdir -p ./docs/handbook/compose
          mv ./docs/sample/build/dist/js/productionExecutable/* ./docs/handbook/compose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-files
          path: ./docs/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build-files
          path: ./docs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          cd docs
          pip install zensical
          zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/site
      - uses: actions/deploy-pages@v4
        id: deployment